# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dict = {}
        for i in t:
            if i in dict:
                dict[i]+=1
            else:
                dict[i] = 1
        for j in s:
            if j in dict:
                dict[j] -= 1
        for key,value in dict.iteritems():
            if value != 0:
                return key